from PIL import Image, ImageDraw, ImageFont
from pathlib import Path
from src.extraction import text_from_pdf
import difflib
import json
import sys

pdf_dir = Path("tests/pdf")
log_path = Path("tests/logs/ocr_log.json")

def _next_pdf_path() -> Path:
    '''
    Makes the path for the next (indexed) test
    '''
    pdf_dir.mkdir(parents=True, exist_ok=True)
    i = 1
    while (pdf_dir / f"test_ocr{i}.pdf").exists():
        i += 1
    return pdf_dir / f"test_ocr{i}.pdf"

def _create_pdf(text: str, path: Path):
    '''
    Creates the PDF file with a text wroted as an image instead of a plain text.
    '''
    img = Image.new("RGB", (1280, 720), color="white")
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", size=12)
    draw.text((50, 80), text, fill="black", font=font)
    img.save(path, "PDF")

def _count_errors(original: str, ocr_text: str) -> int:
    '''
    Counts sequentally the amount of different characters between the original string and the one generated by OCR
    '''
    errors = 0
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, original, ocr_text).get_opcodes():
        if tag != "equal":
            errors += max(i2 - i1, j2 - j1)
    return errors

def _log(original: str, ocr_text: str, errors: int):
    '''
    Generates an entry for an indiviaul OCR test 
    '''
    log_path.parent.mkdir(parents=True, exist_ok=True)
    entries = json.loads(log_path.read_text(encoding="utf-8")) if log_path.exists() else []
    entries.append({"original_text": original, "ocr_text": ocr_text, "error_count": errors})
    log_path.write_text(json.dumps(entries, ensure_ascii=False, indent=2), encoding="utf-8")

def test_ocr(text: str):
    '''
    Complete test pipeline (create pdf + ocr + log)
    '''
    path = _next_pdf_path()
    _create_pdf(text, path)
    ocr_text = text_from_pdf(path).strip()
    errors = _count_errors(text, ocr_text)
    _log(text, ocr_text, errors)
    print(f"Original : {text}")
    print(f"OCR : {ocr_text}")
    print(f"Errors : {errors}")

if __name__ == "__main__":
    test_ocr(sys.argv[1])
